name: Hello World!
on: workflow_dispatch
jobs:
  build-app:
   runs-on: ubuntu-latest
   steps:
     - name: Build step
       run: echo "A demo build!"
  test-app:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Test step
        run: echo "Test phase running"
  deploy-app:
     runs-on: ubuntu-latest
     needs: test-app
     steps:
       - name: Deploy phase
         run: echo "Deployment phase running"
      
        
