name: Hello World!
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Build step
       run: echo "A demo build!"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Test phase running"
  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Deploy phase
         run: echo "Deployment phase running"
      
        
